### PR TITLE
Use wrapping_shr

### PR DESCRIPTION
**Pull request by vivekvpandya**

### CODE REVIEW

**Review by matthiasgoergens — COMMENTED** [review]
Perhaps make this a PR to upstream?

**Comment by vivekvpandya** [comment]
> Perhaps make this a PR to upstream?

yes

**Comment by vivekvpandya** [comment]
created https://github.com/0xPolygonZero/plonky2/pull/1478
only curiosity is that, why its get triggered on WASM32-WASI target?

**Comment by vivekvpandya** [comment]
closing as this work is merged in upstream.

**Pull request closed without merging**
